#!/usr/bin/env bash
source ${HOME}/.bashrc
################################################################################

declare GIT_SOURCE="https://github.com/funtoo"

########################################

if [[ -n "${@}" ]]; then
	export REPDIR="${1}" && shift
	export COMMIT="${1}" && shift
	if [[ -z "${COMMIT}" ]]; then
		COMMIT="HEAD"
	fi
	declare FILE=
	if [[ -d	${REPDIR}/.git ]] && [[ ! -d	${REPDIR}.git ]]; then
		${MV}	${REPDIR}/.git			${REPDIR}.git;
	fi
	if [[ -d	${REPDIR}.git ]] && [[ ! -L	${REPDIR}/.git ]]; then
		${LN}	../$(basename ${REPDIR}).git	${REPDIR}/.git
	fi
	(cd ${REPDIR} &&
		${GIT} checkout --force master &&
		${GIT} pull &&
		${GIT} reset --hard ${COMMIT}
	)
	perl -e '
		use strict;
		use warnings;
		use JSON::XS;
		my $repdir = ${ENV{REPDIR}};
		open(INFO, "<", ${repdir} . "/metadata/kit-info.json")	|| die();
		open(SHA1, "<", ${repdir} . "/metadata/kit-sha1.json")	|| die();
		my $info = do { local $/; <INFO> };
		my $sha1 = do { local $/; <SHA1> };
		$info = decode_json(${info});
		$sha1 = decode_json(${sha1});
		close(INFO)	|| die();
		close(SHA1)	|| die();
		my $order = $info->{"kit_order"};
		foreach my $kit (@{$order}) {
			my $head = $info->{"kit_settings"}{$kit}{"default"};
			my $hash = $sha1->{$kit}{$head};
			print "${kit}|${head}|${hash}\n";
		};
	' -- "${@}" |
	while read -r FILE; do
		declare RKIT=$(echo "${FILE}" | ${SED} "s/^(.+)[|](.+)[|](.+)$/\1/g")
		declare HEAD=$(echo "${FILE}" | ${SED} "s/^(.+)[|](.+)[|](.+)$/\2/g")
		declare HASH=$(echo "${FILE}" | ${SED} "s/^(.+)[|](.+)[|](.+)$/\3/g")
		declare RGIT="${GIT_CMD} --git-dir=${REPDIR}.git/${SCRIPT}/${RKIT}.git --work-tree=${REPDIR}/kits/${RKIT}";
		echo -en "\n[${RKIT} :: ${HEAD} == ${HASH}]\n"
		${MKDIR} ${REPDIR}.git/${SCRIPT}
		if [[ ! -d "${REPDIR}.git/${SCRIPT}/${RKIT}.git" ]]; then
			git-clone ${GIT_SOURCE}/${RKIT}.git ${REPDIR}/kits/${RKIT}
		fi
		if [[ -d	${REPDIR}/kits/${RKIT}/.git ]] && [[ ! -d			${REPDIR}.git/${SCRIPT}/${RKIT}.git ]]; then
			${MV}	${REPDIR}/kits/${RKIT}/.git					${REPDIR}.git/${SCRIPT}/${RKIT}.git
		fi
		if [[ -d	${REPDIR}/kits/${RKIT}.git ]] && [[ ! -d			${REPDIR}.git/${SCRIPT}/${RKIT}.git ]]; then
			${MV}	${REPDIR}/kits/${RKIT}.git					${REPDIR}.git/${SCRIPT}/${RKIT}.git
		fi
		if [[ -d	${REPDIR}.git/${SCRIPT}/${RKIT}.git ]] && [[ ! -L		${REPDIR}/kits/${RKIT}/.git ]]; then
			${LN}	../../../$(basename ${REPDIR}).git/${SCRIPT}/${RKIT}.git	${REPDIR}/kits/${RKIT}/.git
		fi
		if [[ -d	${REPDIR}.git/${SCRIPT}/${RKIT}.git ]] && [[ ! -L		${REPDIR}/kits/${RKIT}.git ]]; then
			${LN}	../../$(basename ${REPDIR}).git/${SCRIPT}/${RKIT}.git		${REPDIR}/kits/${RKIT}.git
		fi
		(cd ${REPDIR}/kits/${RKIT} &&
			${RGIT} checkout --force ${HEAD} &&
			${RGIT} pull &&
			${RGIT} reset --hard ${HASH}
		)
	done
	chown -R portage:portage ${REPDIR}{,.git}
fi

exit 0
################################################################################
# end of file
################################################################################
# http://www.funtoo.org/News:Funtoo-Stable_Going_Away
# http://www.funtoo.org/News:Kits_are_Go_(Switch_to_Them!)
#
# http://www.funtoo.org/News:Better_Experiences:_Ego_and_Vim
# http://www.funtoo.org/News:New_Ports-2017_tree_and_Kits
# http://www.funtoo.org/Ports-2012-to-kits-migration-guide
#
# http://www.funtoo.org/Funtoo_Kits
# http://www.funtoo.org/Funtoo_Linux_Installation
# https://github.com/funtoo/meta-repo
# https://git-scm.com/book/en/v2/Git-Tools-Submodules
#
# https://www.funtoo.org/Funtoo_Profiles
################################################################################
# 2017-08-16 18:57:35 +0000 f6ea76da416341a94ad5ca88dbf4f947e4e7b531 kit updates
f6ea76da416341a94ad5ca88dbf4f947e4e7b531
# 2018-09-08 13:36:35 +0000 776f16598dac814dee59f95a1e21cefe6c612a02 kit updates
776f16598dac814dee59f95a1e21cefe6c612a02
