#!/usr/bin/env bash
source ${HOME}/.bashrc
################################################################################

ISO="$(ls /.g/_data/_target/iso/grml*.iso | tail -n1)"
KRN="/boot/grml64full/vmlinuz"

echo -en "ISO: ${ISO}\n"
echo -en "KRN: ${KRN}\n"

########################################

declare MNT="/mnt/${SCRIPT}"
${MKDIR} ${MNT}

################################################################################

mount -o loop ${ISO} ${MNT}
file ${MNT}${KRN}
/usr/src/linux/scripts/extract-ikconfig ${MNT}${KRN} >${_SELF}.config
if [[ ${?} != 0 ]]; then
	mount | ${GREP} "^${ISO}"
else
	umount ${ISO}
fi

exit 0
################################################################################
# end of file
################################################################################
